version: '3'

services:

  php5.6:
    container_name: php5.6
    build: ./php5.6
    # restart: unless-stopped
    ports:
    - "${PHP_5_6_PORT_80}:80"
    - "${PHP_5_6_PORT_443}:443"
    volumes:
    - ${PROJECTS_PATH}:/var/www/html
    links:
    - mysql5.7
    - mongo4
    - memcached1.5
    - redis5

  php7.2:
    container_name: php7.2
    build: ./php7.2
    # restart: unless-stopped
    ports:
    - "${PHP_7_2_PORT_80}:80"
    - "${PHP_7_2_PORT_443}:443"
    volumes:
    - ${PROJECTS_PATH}:/var/www/html
    links:
    - mysql5.7
    - memcached1.5
    - redis5
    - mongo4

  php7.4:
    container_name: php7.4
    build: ./php7.4
    # restart: unless-stopped
    ports:
    - "${PHP_7_4_PORT_80}:80"
    - "${PHP_7_4_PORT_443}:443"
    volumes:
    - ${PROJECTS_PATH}:/var/www/html
    links:
    - mysql5.7
    - memcached1.5
    - redis5
    - mongo4

  php8.0:
    container_name: php8.0
    build: ./php8.0
    # restart: unless-stopped
    ports:
    - "${PHP_8_0_PORT_80}:80"
    - "${PHP_8_0_PORT_443}:443"
    volumes:
    - ${PROJECTS_PATH}:/var/www/html
    links:
    - mysql5.7
    - memcached1.5
    - redis5
    - mongo4

  mysql5.7:
    container_name: mysql5.7
    build: ./mysql5.7
    ports:
    - "${MYSQL_5_7_PORT}:3306"
    volumes:
    - ./db/mysql:/var/lib/mysql
    environment:
    - MYSQL_HOST=127.0.0.1
    - MYSQL_PORT=3306
    - MYSQL_DATABASE=${DEFAULT_DATABASE}
    - MYSQL_USER=${DEFAULT_USER}
    - MYSQL_PASSWORD=${DEFAULT_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${DEFAULT_ROOT_PASSWORD}

  mongo4:
    container_name: mongo4
    build: ./mongo4
    ports:
    - "${MONGO_4_PORT}:27017"
    volumes:
    - ./db/mongo:/data/db
    environment:
    - MONGODB_ROOT_USERNAME=${DEFAULT_ROOT_USER}
    - MONGODB_ROOT_PASSWORD=${DEFAULT_ROOT_PASSWORD}

  memcached1.5:
      container_name: memcached1.5
      build: ./memcached1.5
      ports:
        - "${MEMCACHED_1_5_PORT}:11211"

  redis5:
    container_name: redis5
    build: ./redis5
    ports:
    - "${REDIS_5_PORT}:6379"
    networks:
      - global-network

networks:
  global-network:
      external: true