version: '3'

services:

  php5.6:
    container_name: php5.6
    build: ./php5.6
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ../dev:/var/www/html
    links:
    - mysql5.7
    - mongo4
    - memcached1.5
    - redis5

  php7.2:
    container_name: php7.2
    build: ./php7.2
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ../dev:/var/www/html
    links:
    - mysql5.7
    - memcached1.5
    - redis5
    - mongo4

  mysql5.7:
    container_name: mysql5.7
    build: ./mysql5.7
    ports:
    - "3306:3306"
    volumes:
    - ../db/mysql:/var/lib/mysql
    environment:
    - MYSQL_HOST=127.0.0.1
    - MYSQL_PORT=3306
    - MYSQL_DATABASE=${DEFAULT_DATABASE}
    - MYSQL_USER=${DEFAULT_USER}
    - MYSQL_PASSWORD=${DEFAULT_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${DEFAULT_ROOT_PASSWORD}

  mongo4:
    container_name: mongo4
    build: ./mongo4
    ports:
    - "27017:27017"
    volumes:
    - ../db/mongo:/data/db
    environment:
    - MONGODB_ROOT_USERNAME=${DEFAULT_ROOT_USER}
    - MONGODB_ROOT_PASSWORD=${DEFAULT_ROOT_PASSWORD}

  memcached1.5:
      container_name: memcached1.5
      build: ./memcached1.5
      ports:
        - "11211:11211"

  redis5:
    container_name: redis5
    build: ./redis5
    ports:
    - "6379:6379"
